import { sendJSON, readJSON } from "../lib/http.js";
import { generateViaAgent, brainstormPrompt, enhancePrompt } from "../services/agentClient.js";
import { parseAgentJSON, parseMarkdownIdeas } from "../lib/ideaMapper.js";
import { CATEGORIES } from "../config.js";

export async function handle(req, res, path) {
  if (req.method === "POST" && path === "/api/brainstorm") {
    try {
      const { topic } = await readJSON(req);
      const reply = await generateViaAgent(brainstormPrompt((topic || "").trim()));
      const parsed = parseAgentJSON(reply);

      if (Array.isArray(parsed)) {
        const ideas = parsed
          .filter((i) => i && (i.title || i.text))
          .map((i) => ({
            title: i.title || i.text || "Untitled",
            description: i.description || "",
            category: CATEGORIES.includes(i.category) ? i.category : "LLM & Agents",
            difficulty: i.difficulty || "Beginner",
            estimatedHours: Math.min(i.estimatedHours || 0.75, 1),
            tags: Array.isArray(i.tags) ? i.tags : ["AIBrainstorm"],
            objectives: Array.isArray(i.objectives) ? i.objectives : [],
          }));
        sendJSON(res, 200, { ideas });
        return true;
      }

      if (reply) {
        const mdIdeas = parseMarkdownIdeas(reply);
        if (mdIdeas.length > 0) {
          const stubs = mdIdeas.slice(0, 5).map((item) => ({
            title: item.title,
            description: item.description || "Generated by RCRT agent.",
            category: CATEGORIES.includes(item.category) ? item.category : "LLM & Agents",
            difficulty: item.difficulty || "Beginner",
            estimatedHours: item.estimatedHours || 0.75,
            tags: ["AIBrainstorm"],
            objectives: [],
          }));
          sendJSON(res, 200, { ideas: stubs });
          return true;
        }
        const stubs = reply
          .split(/\n+/)
          .map((l) => l.replace(/^[\s\-*\d.\)]+/, "").replace(/\*\*/g, "").trim())
          .filter((l) => l.length > 10 && !l.match(/^(Title|Description|Category|Difficulty|Hours):/i))
          .slice(0, 5)
          .map((l) => ({
            title: l.slice(0, 120),
            description: "Generated by RCRT agent.",
            category: "LLM & Agents",
            difficulty: "Beginner",
            estimatedHours: 0.75,
            tags: ["AIBrainstorm"],
            objectives: [],
          }));
        sendJSON(res, 200, { ideas: stubs });
        return true;
      }

      sendJSON(res, 200, { ideas: [] });
    } catch (err) {
      console.error("POST /api/brainstorm error:", err);
      sendJSON(res, 500, { error: err.message || "brainstorm failed" });
    }
    return true;
  }

  if (req.method === "POST" && path === "/api/enhance") {
    try {
      const { title, description } = await readJSON(req);
      const t = (title || "").trim();
      if (!t) { sendJSON(res, 400, { error: "title is required" }); return true; }

      const reply = await generateViaAgent(enhancePrompt(t, description));
      const parsed = parseAgentJSON(reply);

      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        sendJSON(res, 200, {
          title: parsed.title || t,
          description: parsed.description || description || "",
          category: CATEGORIES.includes(parsed.category) ? parsed.category : "LLM & Agents",
          difficulty: parsed.difficulty || "Beginner",
          estimatedHours: Math.min(parsed.estimatedHours || 0.75, 1),
          tags: Array.isArray(parsed.tags) ? parsed.tags : ["AILab"],
          objectives: Array.isArray(parsed.objectives) ? parsed.objectives : [],
        });
      } else {
        sendJSON(res, 200, {
          title: t,
          description: description || `Fast hands-on AI Lab session exploring ${t}.`,
          category: "LLM & Agents",
          difficulty: "Beginner",
          estimatedHours: 0.75,
          tags: ["FastBuild", "AILab"],
          objectives: [`Define scope for ${t}`, "Build prototype in under 1 hour", "Demo to team"],
        });
      }
    } catch (err) {
      console.error("POST /api/enhance error:", err);
      sendJSON(res, 500, { error: err.message || "enhance failed" });
    }
    return true;
  }

  return false;
}
